
sudo: required
services:
- docker
language: bash
script:
#general settings
- >
  OWNER=valentinvieriu
  IMAGE_NAME=alpine-mosquitto-arm
  QNAME=$OWNER/$IMAGE_NAME
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t $QNAME:build .
# test image
- docker run $QNAME:build uname -a
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    export TAG=$(grep "MOSQUITTO_VERSION=" Dockerfile | sed 's/.*MOSQUITTO_VERSION=v//')
    docker tag $QNAME:build $QNAME:$TAG
    docker tag $QNAME:build $QNAME:latest
    docker push $QNAME:$TAG
    docker push $QNAME:latest
  fi